### ISSUE TITLE
error

### ISSUE THREAD

**Issue by zhouwenbin** [tomatau/breko-hub#1]
```
npm ERR! Darwin 15.0.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "dev"
npm ERR! node v5.0.0
npm ERR! npm  v3.3.6
npm ERR! code ELIFECYCLE
npm ERR! breko-hub@0.0.1 dev: `node ./scripts/babel.entry.js --dev`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the breko-hub@0.0.1 dev script 'node ./scripts/babel.entry.js --dev'.
npm ERR! This is most likely a problem with the breko-hub package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node ./scripts/babel.entry.js --dev
npm ERR! You can get their info via:
npm ERR!     npm owner ls breko-hub
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/user/git/breko-hub/npm-debug.log
```

**Comment by tomatau** [comment]
Can you provide more error details?

Also have you created a `.env` file?

Minimum requirements would be:

```
NODE_ENV=development
PORT=1337
DEBUG=
```

**Comment by zhouwenbin** [comment]
```
0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/bin/node', '/usr/local/bin/npm', 'run', 'dev' ]
2 info using npm@3.3.6
3 info using node@v5.0.0
4 verbose run-script [ 'predev', 'dev', 'postdev' ]
5 info lifecycle breko-hub@0.0.1~predev: breko-hub@0.0.1
6 silly lifecycle breko-hub@0.0.1~predev: no script for predev, continuing
7 info lifecycle breko-hub@0.0.1~dev: breko-hub@0.0.1
8 verbose lifecycle breko-hub@0.0.1~dev: unsafe-perm in lifecycle true
9 verbose lifecycle breko-hub@0.0.1~dev: PATH: /usr/local/lib/node_modules/npm/bin/node-gyp-bin:/Users/user/git/breko-hub/node_modules/.bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin
10 verbose lifecycle breko-hub@0.0.1~dev: CWD: /Users/user/git/breko-hub
11 silly lifecycle breko-hub@0.0.1~dev: Args: [ '-c', 'node ./scripts/babel.entry.js --dev' ]
12 silly lifecycle breko-hub@0.0.1~dev: Returned: code: 1  signal: null
13 info lifecycle breko-hub@0.0.1~dev: Failed to exec dev script
14 verbose stack Error: breko-hub@0.0.1 dev: `node ./scripts/babel.entry.js --dev`
14 verbose stack Exit status 1
14 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/lifecycle.js:233:16)
14 verbose stack     at emitTwo (events.js:87:13)
14 verbose stack     at EventEmitter.emit (events.js:172:7)
14 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/spawn.js:24:14)
14 verbose stack     at emitTwo (events.js:87:13)
14 verbose stack     at ChildProcess.emit (events.js:172:7)
14 verbose stack     at maybeClose (internal/child_process.js:818:16)
14 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
15 verbose pkgid breko-hub@0.0.1
16 verbose cwd /Users/user/git/breko-hub
17 error Darwin 15.0.0
18 error argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "dev"
19 error node v5.0.0
20 error npm  v3.3.6
21 error code ELIFECYCLE
22 error breko-hub@0.0.1 dev: `node ./scripts/babel.entry.js --dev`
22 error Exit status 1
23 error Failed at the breko-hub@0.0.1 dev script 'node ./scripts/babel.entry.js --dev'.
23 error This is most likely a problem with the breko-hub package,
23 error not with npm itself.
23 error Tell the author that this fails on your system:
23 error     node ./scripts/babel.entry.js --dev
23 error You can get their info via:
23 error     npm owner ls breko-hub
23 error There is likely additional logging output above.
24 verbose exit [ 1, true ]
```

**Comment by tomatau** [comment]
Did you do a fresh install of node_modules on npm 3.3.x?

I can't reproduce this... 

Maybe you're behind some firewall? If a fresh node_modules install doesn't work, try with sudo...

**Comment by xdbr** [comment]
I have seen the same as @zhouwenbin. 

@tomatau: I can prove that the above mentioned `.env` file does the trick for me.

Mentioning that sample file in the README might help to remove friction for new users, though.

**Comment by tomatau** [comment]
Thanks @xdbr - it is in the readme but I'll make it more obvious :)

**Comment by zhouwenbin** [comment]
@tomatau ok,it works when i add '.env' file. i think you should push the file to github.

**Comment by tomatau** [comment]
The purpose of an .env file is to store environmental settings such as AUTH_CODE and other private information.

I'll make the .env file a non requirement and default NODE_ENV to development and some default port.

**Comment by tomatau** [comment]
https://github.com/tomatau/breko-hub/pull/3
