### ISSUE TITLE
npm test error

### ISSUE THREAD

**Issue by xdbr** [tomatau/breko-hub#2]
Similar to #1, `npm run` doesn't run out of the box after a fresh install.

This is especially bad for people trying out this stack.

The `.env` file as in #1 doesn't help here – might it be a similarly simple issue that does the polishing?

This is what I'm getting:

```
npm test

> breko-hub@0.0.1 test /Users/dbr/code/github/breko-hub
> node ./scripts/babel.entry.js --test

module.js:338
    throw err;
    ^

Error: Cannot find module './/webpack.config'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:286:25)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/Users/dbr/code/github/breko-hub/src/config/webpack.unit-test.browser.config.js:5:52)
    at Module._compile (module.js:434:26)
    at normalLoader (/Users/dbr/code/github/breko-hub/node_modules/babel-core/lib/api/register/node.js:199:5)
    at Object.require.extensions.(anonymous function) [as .js] (/Users/dbr/code/github/breko-hub/node_modules/babel-core/lib/api/register/node.js:216:7)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/Users/dbr/code/github/breko-hub/scripts/test.js:4:26)
    at Module._compile (module.js:434:26)
    at normalLoader (/Users/dbr/code/github/breko-hub/node_modules/babel-core/lib/api/register/node.js:199:5)
    at Object.require.extensions.(anonymous function) [as .js] (/Users/dbr/code/github/breko-hub/node_modules/babel-core/lib/api/register/node.js:216:7)
npm ERR! Test failed.  See above for more details.
```

**Comment by tomatau** [comment]
Thanks @xdbr - I'll be looking into this ASAP, just in the process of moving house. Sorry for the problems, I've only been doing installs on one machine so it definitely needs some polish :)

**Comment by tomatau** [comment]
Actually I can see the problem from the error, I changed the file name from `webpack.config` to `webpack.base.config` and didn't update the reference in `src/config/webpack.unit-test.browser.config`. Will fix this asap but it's easy to fix locally too :)

**Comment by tomatau** [comment]
@xdbr, tests are working again on latest master now.

**Comment by xdbr** [comment]
Yes, can confirm it works with #4

**Comment by tomatau** [comment]
Where is the bluebird dependency coming from? Works fine for me without it.
